# Generated by Django 4.1.3 on 2022-12-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_unit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
        ),
    ]
